use_frameworks!

source 'https://github.com/CocoaPods/Specs.git' #include this if you will be referencing any public pods!

target 'NFImageView_Example' do
  pod 'NFImageView', :path => '../'
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'NFImageView_Tests' do
    inherit! :search_paths

    
  end
end
