platform :ios, '13.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git' #include this if you will be referencing any public pods!

target 'NFImageView_Example' do
  pod 'NFImageView', :path => '../'
  pod 'Alamofire', '~> 5.1'
  pod 'AlamofireImage', '~> 4.1'

  target 'NFImageView_Tests' do
    inherit! :search_paths

  end
end

# Workaround for @IBDesignable (https://github.com/CocoaPods/CocoaPods/issues/5334)
post_install do |installer|
  installer.pods_project.targets.each do |target|
    next if target.product_type == "com.apple.product-type.bundle"
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
